### ISSUE TITLE
Feature request: Show first or n classes

### ISSUE THREAD

**Issue by TPJelf** [Etsi0/class-collapse#10]
Hi, I'm loving your extension but I find myself sometimes lost in nested divs, would It be possible to allow for 1 or n classes to be visible and hide the rest to ease glance readability? I tried using regex but failed miserably.

Thanks and regards

**Comment by Etsi0** [comment]
is this what you are looking for? if yes, i will push it up to main.
```
["body", "red", "grid"]
```
![image](https://github.com/Etsi0/class-collapse/assets/43541844/5dc5088d-2bb3-4566-bdc2-fca43a69e982)
![image](https://github.com/Etsi0/class-collapse/assets/43541844/6d716b8c-1242-4776-8523-349f7c6cb9be)

**Comment by TPJelf** [comment]
This is looking great! Maybe the partial hits like body for text-body can be specified with asterisks? (*body for text-body for example)

Also would it be possible to remove the leading "..." in full hits on first classes like grid in your screenshots?

I'm sorry if I'm too nit-picky! Thanks again!

**Comment by Etsi0** [comment]
Hi again,

I made it so it shows the hold thing instead of just the word. for example, if you want to see "body" you see `text-body`

The `...` indicates collapsed content (the default value for `class-collapse.collapsedText`). You can change this setting, but it will affect all instances.

![image](https://github.com/Etsi0/class-collapse/assets/43541844/abab68da-7b37-46f2-88c1-b5a613f7f632)

**Comment by TPJelf** [comment]
Not having exact matches makes it a bit noisy. Partial matches are great, but being able to support both would allow for a cleaner interface. What do you think?

Thanks again!

**Comment by TPJelf** [comment]
Thanks for the release!
